<template>
	<div class="relative flex justify-center">
		<div class="flex w-full justify-center">
			<blockquote class="col italic border-l-4 border-black quote text-left justify-center pl-5">
				<p class="text-justify flex flex wrap text-3xl">
					" Poète et bien des choses "
				</p>
				<div class="relative flex italic absolute text-1xl pt-4">
					<cite> Jiani Abert, Ecrivain amateur </cite>
				</div>
			</blockquote>
		</div>
	</div>
</template>

<script>
export default {
	name: 'CitationVue',
}
</script>

<style lang="scss" scoped></style>
