<template>
	<div class="relative flex justify-center">
		<div class="flex w-1/2">
			<blockquote class="col italic border-l-4 border-black quote text-left justify-center pl-5">
				<p class="text-justify flex flex wrap">
					Lorem Ipsum is simply dummy text of the printing anddzez zefffffffffd fd fezr fedsfezdsfezsfezfdezf er er gere terdf ezdf ezdez dez dez typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the
					1500s, when an unknown printer took a galley of type and scrambled it.
				</p>
				<div class="relative flex italic absolute pt-4">
					<cite> Jiani Abert, Ecrivain amateur </cite>
				</div>
			</blockquote>
		</div>
	</div>
</template>

<script>
export default {
	name: 'CitationVue',
}
</script>

<style></style>
